# Generated by Django 3.1.7 on 2021-02-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_storeinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
    ]
